[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
address = "127.0.0.1"
port = 1420
open = false

# [[hooks]]
# # THIS IS SO FUCKING IMPORTANT FOR TAILWIND
# stage = "pre_build"
# command = "nu"
# command_arguments = ["-c", "npx tailwindcss -i ./src/input.css -o ./output.css"]
